version: "3.8"

services:
  postgres:
    image: postgres
    command: -c 'max_connections=600'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5434:5432"
    networks:
      - backend

    # authBot:
    #   build: ./auth-bot
    #   image: auth_bot:latest
    #   environment:
    #     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    #     PROFILES_URL: ${PROFILES_URL}
    #   depends_on:
    #     - profileService

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: