// Mocks generated by Mockito 5.4.6 from annotations
// in solar_wind_flutter_app/test/features/feed/presentation/screen/user_profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:solar_wind_flutter_app/features/feed/data/models/user.dart'
    as _i2;
import 'package:solar_wind_flutter_app/features/feed/data/services/like_service.dart'
    as _i6;
import 'package:solar_wind_flutter_app/features/feed/data/services/profile_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i4.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> fetchUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [userId]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#fetchUser, [userId])),
            ),
          )
          as _i5.Future<_i2.User>);
}

/// A class which mocks [LikeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikeService extends _i1.Mock implements _i6.LikeService {
  MockLikeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i5.Future<void> likeUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#likeUser, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
