name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    
    - name: Install dependencies
      run: |
        cd frontend/solar_wind_flutter_app
        flutter pub get
        
    - name: Build web
      run: |
        cd frontend/solar_wind_flutter_app
        flutter build web --release --base-href /SOLAR_WIND_REPO_NAME/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/solar_wind_flutter_app/build/web
        keep_files: true
